[phases.setup]
nixPkgs = ["...", "openjdk21"]

[phases.build]
cmds = [
  "chmod +x mvnw",
  "./mvnw clean compile -DskipTests",
  "./mvnw package -DskipTests"
]

[start]
cmd = "java -Dserver.port=$PORT -jar target/gestao-psi-backend-1.0.0.jar"

